<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>webservice项目接口测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">webservice项目接口测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> lyx</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-08-21 17:57:07</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:09.043073</p>
<p class='attribute'><strong>测试结果 : </strong> 共 29，通过 8，失败 21，通过率= 27.59%</p>

<p class='description'>发送短信验证码接口、注册接口、实名认证接口</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 27.59% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 21 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 8 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 29 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='failClass warning'>
    <td>test_01_sendmcode.TestSendMCode</td>
    <td class="text-center">9</td>
    <td class="text-center">2</td>
    <td class="text-center">7</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',9)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_send_m_code_1_发送短信验证码成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='failCase'><div class='testcase'>test_send_m_code_2_ip地址为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: &lt;suds.sax.document.Document object at 0x09078EB0&gt;
Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 78, in test_send_m_code
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 70, in test_send_m_code
    self.assertEqual(case["expected"], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"faultcode": "soap:Server", "faultstring": "用户IP不能为空"}'
- {"retCode": "0", "retInfo": "ok"}
+ {"faultcode": "soap:Server", "faultstring": "用户IP不能为空"}



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='failCase'><div class='testcase'>test_send_m_code_3_tmpl_id为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>失败</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: &lt;suds.sax.document.Document object at 0x090C2F90&gt;
Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 78, in test_send_m_code
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 70, in test_send_m_code
    self.assertEqual(case["expected"], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"faultcode": "soap:Client", "faultstring":[46 chars]" "}'
- {"retCode": "0", "retInfo": "ok"}
+ {"faultcode": "soap:Client", "faultstring": "Unmarshalling Error: For input string: \"\" "}



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='failCase'><div class='testcase'>test_send_m_code_4_mobile为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: &lt;suds.sax.document.Document object at 0x090553F0&gt;
Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 78, in test_send_m_code
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 70, in test_send_m_code
    self.assertEqual(case["expected"], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"faultcode": "soap:Server", "faultstring": "手机号码错误"}'
- {"retCode": "0", "retInfo": "ok"}
+ {"faultcode": "soap:Server", "faultstring": "手机号码错误"}



    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_send_m_code_5_ip地址格式不正确</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='failCase'><div class='testcase'>test_send_m_code_6_ip地址超出范围</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: &lt;suds.sax.document.Document object at 0x090CE2F0&gt;
Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 78, in test_send_m_code
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 70, in test_send_m_code
    self.assertEqual(case["expected"], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"faultcode": "soap:Server", "faultstring": "手机号码错误"}'
- {"retCode": "0", "retInfo": "ok"}
+ {"faultcode": "soap:Server", "faultstring": "手机号码错误"}



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='failCase'><div class='testcase'>test_send_m_code_7_mobile不足11位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>失败</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>失败</button>
    <div id='div_ft1_7' class="collapse in" align="left">
    <pre>
    
ft1_7: &lt;suds.sax.document.Document object at 0x08DCD590&gt;
Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 78, in test_send_m_code
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 70, in test_send_m_code
    self.assertEqual(case["expected"], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"faultcode": "soap:Server", "faultstring": "手机号码错误"}'
- {"retCode": "0", "retInfo": "ok"}
+ {"faultcode": "soap:Server", "faultstring": "手机号码错误"}



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='failCase'><div class='testcase'>test_send_m_code_8_mobile多于11位</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse in" align="left">
    <pre>
    
ft1_8: &lt;suds.sax.document.Document object at 0x08D4DD70&gt;
Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 78, in test_send_m_code
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 70, in test_send_m_code
    self.assertEqual(case["expected"], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"faultcode": "soap:Server", "faultstring": "手机号码错误"}'
- {"retCode": "0", "retInfo": "ok"}
+ {"faultcode": "soap:Server", "faultstring": "手机号码错误"}



    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_9' class='none'>
    <td class='failCase'><div class='testcase'>test_send_m_code_9_mobile为整型</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_9'>失败</button>
    <div id='div_ft1_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_9'>失败</button>
    <div id='div_ft1_9' class="collapse in" align="left">
    <pre>
    
ft1_9: &lt;suds.sax.document.Document object at 0x091475F0&gt;
Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 78, in test_send_m_code
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_01_sendmcode.py", line 70, in test_send_m_code
    self.assertEqual(case["expected"], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"faultcode": "soap:Server", "faultstring": "手机号码错误"}'
- {"retCode": "0", "retInfo": "ok"}
+ {"faultcode": "soap:Server", "faultstring": "手机号码错误"}



    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>test_02_register.TestRegister</td>
    <td class="text-center">13</td>
    <td class="text-center">3</td>
    <td class="text-center">10</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',13)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='pt2_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_regiester_01_发送验证码</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt2_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_regiester_02_注册成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_03_已注册号码再次注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>失败</button>
    <div id='div_ft2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>失败</button>
    <div id='div_ft2_3' class="collapse in" align="left">
    <pre>
    
ft2_3: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "20042023", "retInfo": "该手机号已被注册"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_4' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_04_已注册用户名再次注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>失败</button>
    <div id='div_ft2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_4'>失败</button>
    <div id='div_ft2_4' class="collapse in" align="left">
    <pre>
    
ft2_4: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "20042003", "retInfo": "该用户已存在"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_regiester_05_发送验证码</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft2_6' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_06_错误验证码</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_6'>失败</button>
    <div id='div_ft2_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_6'>失败</button>
    <div id='div_ft2_6' class="collapse in" align="left">
    <pre>
    
ft2_6: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "30010008", "retInfo": "验证码错误"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_7' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_07_验证码为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_7'>失败</button>
    <div id='div_ft2_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_7'>失败</button>
    <div id='div_ft2_7' class="collapse in" align="left">
    <pre>
    
ft2_7: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "19001", "retInfo": "验证码错误"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_8' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_08_错误手机号</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_8'>失败</button>
    <div id='div_ft2_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_8'>失败</button>
    <div id='div_ft2_8' class="collapse in" align="left">
    <pre>
    
ft2_8: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "19001", "retInfo": "手机号错误"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_9' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_09_用户名为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_9'>失败</button>
    <div id='div_ft2_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_9'>失败</button>
    <div id='div_ft2_9' class="collapse in" align="left">
    <pre>
    
ft2_9: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "19001", "retInfo": "用户名错误"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_10' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_10_渠道信息为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_10'>失败</button>
    <div id='div_ft2_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_10'>失败</button>
    <div id='div_ft2_10' class="collapse in" align="left">
    <pre>
    
ft2_10: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "19001", "retInfo": "渠道信息错误"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_11' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_11_登录密码为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_11'>失败</button>
    <div id='div_ft2_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_11'>失败</button>
    <div id='div_ft2_11' class="collapse in" align="left">
    <pre>
    
ft2_11: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "19001", "retInfo": "用户UID错误"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_12' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_12_手机号为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_12'>失败</button>
    <div id='div_ft2_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_12'>失败</button>
    <div id='div_ft2_12' class="collapse in" align="left">
    <pre>
    
ft2_12: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "19001", "retInfo": "手机号错误"}'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_13' class='none'>
    <td class='failCase'><div class='testcase'>test_regiester_13_ip地址为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_13'>失败</button>
    <div id='div_ft2_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_13'>失败</button>
    <div id='div_ft2_13' class="collapse in" align="left">
    <pre>
    
ft2_13: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 105, in test_regiester
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_02_register.py", line 73, in test_regiester
    self.assertIn("ok", res)
AssertionError: 'ok' not found in '{"retCode": "19001", "retInfo": "IP地址错误"}'


    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>test_03_verified_user_auth.TestUserAuth</td>
    <td class="text-center">7</td>
    <td class="text-center">3</td>
    <td class="text-center">4</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',7)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='pt3_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_verify_user_auth_1_发送验证码</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt3_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_verify_user_auth_2_注册成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt3_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_verify_user_auth_3_实名认证成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft3_4' class='none'>
    <td class='failCase'><div class='testcase'>test_verify_user_auth_4_用户Uid为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_4'>失败</button>
    <div id='div_ft3_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_4'>失败</button>
    <div id='div_ft3_4' class="collapse in" align="left">
    <pre>
    
ft3_4: &lt;suds.sax.document.Document object at 0x092BDA70&gt;
Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_03_verified_user_auth.py", line 119, in test_verify_user_auth
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_03_verified_user_auth.py", line 88, in test_verify_user_auth
    self.assertEqual(case['expected'], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"faultcode": "soap:Client", "faultstring":[46 chars]" "}'
- {"retCode": "0", "retInfo": "ok"}
+ {"faultcode": "soap:Client", "faultstring": "Unmarshalling Error: For input string: \"\" "}



    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_5' class='none'>
    <td class='failCase'><div class='testcase'>test_verify_user_auth_5_真实姓名为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_5'>失败</button>
    <div id='div_ft3_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_5'>失败</button>
    <div id='div_ft3_5' class="collapse in" align="left">
    <pre>
    
ft3_5: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_03_verified_user_auth.py", line 119, in test_verify_user_auth
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_03_verified_user_auth.py", line 88, in test_verify_user_auth
    self.assertEqual(case['expected'], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"retCode": "19001", "retInfo": "真实姓名错误"}'
- {"retCode": "0", "retInfo": "ok"}
?                              ^^
+ {"retCode": "19001", "retInfo": "真实姓名错误"}
?              ++ ++               ^^^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_6' class='none'>
    <td class='failCase'><div class='testcase'>test_verify_user_auth_6_身份证号为空</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_6'>失败</button>
    <div id='div_ft3_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_6'>失败</button>
    <div id='div_ft3_6' class="collapse in" align="left">
    <pre>
    
ft3_6: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_03_verified_user_auth.py", line 119, in test_verify_user_auth
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_03_verified_user_auth.py", line 88, in test_verify_user_auth
    self.assertEqual(case['expected'], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"retCode": "19001", "retInfo": "身份证号错误"}'
- {"retCode": "0", "retInfo": "ok"}
?                              ^^
+ {"retCode": "19001", "retInfo": "身份证号错误"}
?              ++ ++               ^^^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_7' class='none'>
    <td class='failCase'><div class='testcase'>test_verify_user_auth_7_用户Uid不存在</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_7'>失败</button>
    <div id='div_ft3_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_7'>失败</button>
    <div id='div_ft3_7' class="collapse in" align="left">
    <pre>
    
ft3_7: Traceback (most recent call last):
  File "D:\PythonLearning\WebService_Api_Test\libs\ddt.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "D:\PythonLearning\WebService_Api_Test\cases\test_03_verified_user_auth.py", line 119, in test_verify_user_auth
    raise e
  File "D:\PythonLearning\WebService_Api_Test\cases\test_03_verified_user_auth.py", line 88, in test_verify_user_auth
    self.assertEqual(case['expected'], res)
AssertionError: '{"retCode": "0", "retInfo": "ok"}' != '{"retCode": "19001", "retInfo": "身份证号检验错误"}'
- {"retCode": "0", "retInfo": "ok"}
?                              ^^
+ {"retCode": "19001", "retInfo": "身份证号检验错误"}
?              ++ ++               ^^^^^^^^



    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>29</td>
    <td>8</td>
    <td>21</td>
    <td>0</td>
    <td>通过率：27.59%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
